# Generated by Django 2.2.1 on 2019-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='maps_url',
            field=models.CharField(default='None', max_length=1025),
        ),
    ]
