# Generated by Django 2.2.1 on 2019-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0002_eglise_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='tag',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
