# Generated by Django 2.0.2 on 2019-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_jumbotron_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumbotron',
            name='texte',
            field=models.TextField(),
        ),
    ]
