# Generated by Django 2.2.1 on 2019-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190512_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumbotron',
            name='jumbo_url',
            field=models.CharField(max_length=1025, null=True),
        ),
    ]
